# Generated by Django 5.1.1 on 2024-10-11 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=25)),
                ('contrasenia', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='imagen',
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(default='sin categoría', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ADMINxUSUARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=20, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('id_colaborador_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='ADMINxPOST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=20, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('id_post_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('id_colaborador_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='ADMINxCOMENTARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=20, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('id_colaborador_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.colaborador')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='administrado',
            field=models.ManyToManyField(blank=True, through='posts.ADMINxPOST', to='posts.colaborador'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('valoraciones', models.IntegerField(null=True)),
                ('administrado', models.ManyToManyField(blank=True, through='posts.ADMINxCOMENTARIO', to='posts.colaborador')),
            ],
        ),
        migrations.AddField(
            model_name='adminxcomentario',
            name='id_comentario_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comentario'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=25)),
                ('contrasenia', models.CharField(max_length=30)),
                ('administrado', models.ManyToManyField(blank=True, through='posts.ADMINxUSUARIO', to='posts.colaborador')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.usuario'),
        ),
        migrations.AddField(
            model_name='adminxusuario',
            name='id_usuario_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.usuario'),
        ),
        migrations.AddField(
            model_name='post',
            name='usuario_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.usuario'),
        ),
    ]
