# Generated by Django 5.1.1 on 2024-10-19 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_colaborador_rename_image_post_imagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='administrado',
        ),
        migrations.RemoveField(
            model_name='adminxpost',
            name='id_colaborador_FK',
        ),
        migrations.RemoveField(
            model_name='adminxpost',
            name='id_post_FK',
        ),
        migrations.RemoveField(
            model_name='post',
            name='administrado',
        ),
        migrations.RemoveField(
            model_name='adminxusuario',
            name='id_colaborador_FK',
        ),
        migrations.RemoveField(
            model_name='adminxusuario',
            name='id_usuario_FK',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='administrado',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario_FK',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usuario_FK',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='valoraciones',
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='posts.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ADMINxCOMENTARIO',
        ),
        migrations.DeleteModel(
            name='ADMINxPOST',
        ),
        migrations.DeleteModel(
            name='ADMINxUSUARIO',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
